version: '3.8'

services:
  artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-pro:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - JF_SHARED_DATABASE_TYPE=postgresql
      - JF_SHARED_DATABASE_DRIVER=org.postgresql.Driver
      - JF_SHARED_DATABASE_URL=jdbc:postgresql://postgres:5432/artifactory
      - JF_SHARED_DATABASE_USER=artifactory
      - JF_SHARED_DATABASE_PASSWORD=artifactorypass
    depends_on:
      - postgres
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      - artifactory_config:/etc/opt/jfrog/artifactory

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: artifactorypass
      POSTGRES_DB: artifactory
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  artifactory_data:
  artifactory_config:
  postgres_data:
